 install.packages("onewaytests")

install.packages("leaps")


library(openxlsx)
library(onewaytests)
library(sjPlot)
library(corrplot)  
library(officer)
library(flextable)
library(table1) 
library(boot)
library(ggplot2)
library(readxl)
library(bruceR)
library(corrplot)   
library(RColorBrewer) 

rm(list = ls())
#函数部分
sxb <- function(data) {
    # 获取第一列的分类变量
    groups <- unique(data[[1]])
    # 创建一个空的结果数据框
    result <- data.frame(matrix(NA, nrow = ncol(data) - 1, ncol = 4))
    colnames(result) <- c(groups[1], groups[2], "t/z", "p")
    rownames(result) <- colnames(data)[-1]
    # 遍历除第一列之外的所有变量
    for (i in 2:ncol(data)) {
        variable <- colnames(data)[i]
        values_a <- data[data[[1]] == groups[1], i]
        values_b <- data[data[[1]] == groups[2], i]
        n1 <- length(values_a)
        n2 <- length(values_b)
        if (is.numeric(values_a) && is.numeric(values_b)) {
            # 检查每组至少有两个观察值
            if (length(values_a) >= 2 && length(values_b) >= 2 && length(values_a) <= 5000 && length(values_b) <= 5000) {     
                if (shapiro.test(values_a)$p.value > 0.05 && shapiro.test(values_b)$p.value > 0.05) {
                    result[variable, groups[1]] <- paste(format(mean(values_a), digits = 2), "±", format(round(sd(values_a), digits = 2), digits = 2))
                    result[variable, groups[2]] <- paste(format(mean(values_b), digits = 2), "±", format(round(sd(values_b), digits = 2), digits = 2))
                    test_result <- t.test(values_a, values_b)
                    t <- sprintf("%.3f", test_result$statistic)
                    result[variable, "t/z"] <- t
                    result[variable, "t/z"] <- paste(result[variable, "t/z"], "‡")
                } else {
                    # 如果数据不服从正态分布或方差不相等
                   result[variable, groups[1]] <- paste(format(median(values_a), digits = 2), "[", format(diff(quantile(values_a, c(0.25, 0.75))), digits = 2), "]")
          result[variable, groups[2]] <- paste(format(median(values_b), digits = 2), "[", format(diff(quantile(values_b, c(0.25, 0.75))), digits = 2), "]")
                    test_result <- wilcox.test(values_a, values_b)
                    z = (test_result$statistic - (n1*n2/2))/(sqrt((n1*n2*(n1+n2+1))/12))
                    result[variable, "t/z"] <- sprintf("%.3f", z)
                    result[variable, "t/z"] <- paste(result[variable, "t/z"], "†")
                }
                p <- test_result$p.value
                # 根据p值添加显著性标记
                if (p == "<0.001") {
                    result[variable, "p"] <- paste(p, "***")
                } else if (p < 0.01) {
                    result[variable, "p"] <- paste(p, "**")
                } else if (p < 0.05) {
                    result[variable, "p"] <- paste(p, "*")
                } else {
                    result[variable, "p"] <- p
                }
            }
        }
    }
    return(result)
}



df=read_excel("原始数据.xlsx",col_names = TRUE)
df <- as.data.frame(df)
rownames(df) = df[,1]
df = df[,-1]
df1=df[,c(1,2:45)]


result <- sxb(df1)
print(result)
# 将行名添加在第一列
result$RowNames <- rownames(result)
# 将其余4列向后移动一列
result <- cbind(result[, 5], result[, 1:4])
# 删除原始的行名列
result$RowNames <- NULL
# 将第一列的列名设置为空
colnames(result)[1] <- "变量"
table_output <- tab_df(result)
print(table_output)

df=read_excel("原始数据.xlsx",col_names = TRUE)
df <- as.data.frame(df)
rownames(df) = df[,1]
df = df[,-1]

df2=df[1:43,c(5,2:4,9:25)]
df2$l1=log(df2$`TNF-a`)
df2$l2=log(df2$`IL-6`)
df2$l3=log(df2$`Claudin-5`)
df2$l4=log(df2$Zonulin)
df2=df2[c(-12),]

result <- sxb(df2)
print(result)

# 将行名添加在第一列
result$RowNames <- rownames(result)
# 将其余4列向后移动一列
result <- cbind(result[, 5], result[, 1:4])
# 删除原始的行名列
result$RowNames <- NULL
# 将第一列的列名设置为空
colnames(result)[1] <- "变量"
table_output <- tab_df(result)
print(table_output)


df=read_excel("原始数据 2.xlsx",col_names = TRUE)
df <- as.data.frame(df)
rownames(df) = df[,1]
df = df[,-1]
df1=df[,c(1:4,7,10:26)]
result <- sxb(df1)
print(result)# 将行名添加在第一列
result$RowNames <- rownames(result)
# 将其余4列向后移动一列
result <- cbind(result[, 5], result[, 1:4])
# 删除原始的行名列
result$RowNames <- NULL
# 将第一列的列名设置为空
colnames(result)[1] <- "变量"
table_output <- tab_df(result)
print(table_output)

df=read_excel("原始数据3.xlsx",col_names = TRUE)
df <- as.data.frame(df)
rownames(df) = df[,1]
df = df[,-1]
df1=df[,c(1:4,7,10:26)]
result <- sxb(df1)
print(result)# 将行名添加在第一列
result$RowNames <- rownames(result)
# 将其余4列向后移动一列
result <- cbind(result[, 5], result[, 1:4])
# 删除原始的行名列
result$RowNames <- NULL
# 将第一列的列名设置为空
colnames(result)[1] <- "变量"
table_output <- tab_df(result)
print(table_output)

df=read_excel("原始数据4.xlsx",col_names = TRUE)
df <- as.data.frame(df)
rownames(df) = df[,1]
df = df[,-1]
df1=df[,c(1:4,7,10:26)]
result <- sxb(df1)
print(result)# 将行名添加在第一列
result$RowNames <- rownames(result)
# 将其余4列向后移动一列
result <- cbind(result[, 5], result[, 1:4])
# 删除原始的行名列
result$RowNames <- NULL
# 将第一列的列名设置为空
colnames(result)[1] <- "变量"
table_output <- tab_df(result)
print(table_output)

df=read_excel("原始数据5.xlsx",col_names = TRUE)
df <- as.data.frame(df)
rownames(df) = df[,1]
df = df[,-1]
df1=df[,c(1:4,7,10:26)]
result <- sxb(df1)
print(result)# 将行名添加在第一列
result$RowNames <- rownames(result)
# 将其余4列向后移动一列
result <- cbind(result[, 5], result[, 1:4])
# 删除原始的行名列
result$RowNames <- NULL
# 将第一列的列名设置为空
colnames(result)[1] <- "变量"
table_output <- tab_df(result)
print(table_output)

df=read_excel("原始数据6.xlsx",col_names = TRUE)
df <- as.data.frame(df)
rownames(df) = df[,1]
df = df[,-1]
df1=df[,c(1:4,7,10:26)]
result <- sxb(df1)
print(result)# 将行名添加在第一列
result$RowNames <- rownames(result)
# 将其余4列向后移动一列
result <- cbind(result[, 5], result[, 1:4])
# 删除原始的行名列
result$RowNames <- NULL
# 将第一列的列名设置为空
colnames(result)[1] <- "变量"
table_output <- tab_df(result)
print(table_output)

