library(mediation)
library(readxl)
library(ggplot2)

rm(list = ls())

df=read_excel("ALL.xlsx",col_names = TRUE)

df=subset(df, group == "AN")
fit.totaleffect=lm(`Global score`~`emotional abuse`,df)
summary(fit.totaleffect)
fit.mediator=lm(mean~`emotional abuse`,df)
summary(fit.mediator)
fit.dv=lm(`Global score`~`emotional abuse`+mean,df)
summary(fit.dv)
results1 = mediate(fit.mediator, fit.dv, treat='emotional abuse', mediator='mean', boot=T)
summary(results1)

df=subset(df, group == "AN")
fit.totaleffect=lm(`Global score`~cohesion,df)
summary(fit.totaleffect)
fit.mediator=lm(mean~cohesion,df)
summary(fit.mediator)
fit.dv=lm(`Global score`~cohesion+mean,df)
summary(fit.dv)
results2 = mediate(fit.mediator, fit.dv, treat='cohesion', mediator='mean', boot=T)
summary(results2)

df=subset(df, group == "AN")
fit.totaleffect=lm(`Global score`~expressiveness,df)
summary(fit.totaleffect)
fit.mediator=lm(mean~expressiveness,df)
summary(fit.mediator)
fit.dv=lm(`Global score`~expressiveness+mean,df)
summary(fit.dv)
results3 = mediate(fit.mediator, fit.dv, treat='expressiveness', mediator='mean', boot=T)
summary(results3)

summary(results1)
summary(results2)
summary(results3)

library(ggplot2)

# 创建基础图层和散点图层
ggplot(df, aes(y = mean, x = cohesion)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  theme_classic() +
  labs(y = "mean LEP methylation level [%]")

ggplot(df, aes(y = mean, x = expressiveness)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  theme_classic() +
  labs(y = "mean LEP methylation level [%]")

ggplot(df, aes(y = mean, x =`Global score`)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  theme_classic() +
  labs(y = "mean LEP methylation level [%]",x="EDE-Q global score")

