install.packages("reshape2")
install.packages("ggplot2")
install.packages("dplyr")

library(graphics)
library(PerformanceAnalytics)
library(sjPlot)
library(reshape2)
library(dplyr)
library(ggplot2)
library(readxl)
rm(list = ls())#清空数据
#函数部分
splitheatmap <- function(df1, m, method, n) {
  x <- ncol(df1)
  var1 <- colnames(df1)[1:m]
  var2 <- colnames(df1)[(m+1):x]
  cor_matrix <- matrix(NA, nrow = x - m, ncol = m)
  pvalue_matrix <- matrix(NA, nrow = x - m, ncol = m) 
  for (i in 1:m) {
    for (j in 1:(x - m)) {
      if (method == "pearson") {
        cor_test <- cor.test(df1[, var1[i]], df1[, var2[j]])
      } else if (method == "spearman") {
        cor_test <- cor.test(df1[, var1[i]], df1[, var2[j]], method = "spearman")
      } else {
        cat("Invalid value for 'method'. Please use 'pearson' or 'spearman'.")
        return(NULL)
      }
      cor_matrix[j, i] <- cor_test$estimate
      pvalue_matrix[j, i] <- cor_test$p.value
    }
  }
  o <- colnames(df1[, 1:m])
  p <- colnames(df1[, (m + 1):x])
  cor_matrix <- data.frame(cor_matrix)
  row.names(cor_matrix) <- p
  names(cor_matrix) <- o
  cor_matrix <- as.matrix(cor_matrix) 
  if (n == 1) {
    cor <- reshape2::melt(cor_matrix, na.rm = TRUE)
    pval <- reshape2::melt(pvalue_matrix, na.rm = TRUE)
    corr <- cbind(cor, pval[, 3])
    names(corr) <- c("y", "x", "c", "z")
    s <- ggplot2::ggplot(data = corr, ggplot2::aes(x, y, fill = c)) +
      ggplot2::geom_tile() +
      ggplot2::scale_fill_gradient2(
        low = "blue", high = "red", mid = "white", midpoint = 0,
        limit = c(-1, 1), space = "Lab", name = "Correlation"
      ) +
      ggplot2::theme_minimal() +
      ggplot2::theme(
        axis.text.x = ggplot2::element_text(
          angle = 45, vjust = 1, size = 12, hjust = 1
        )
      ) +
      ggplot2::coord_fixed() +
      ggplot2::geom_text(
        aes(
          label = dplyr::case_when(
            z > 0.01 & z <= 0.05 ~ "*",
            z > 0.001 & z <= 0.01 ~ "**",
            z <= 0.001 ~ "***",
            TRUE ~ ""
          )
        ),
        color = "black", size = 10
      )
    print(s)
  } else if (n == 2) {
    cat("\nCorrelation Matrix:\n")
    print(cor_matrix)
  } else if (n == 3) {
    cat("\nP-value Matrix:\n")
    print(pvalue_matrix)
  } else {
    cat("Invalid value for 'n'. Please use 1 for heatmap, 2 for correlation matrix, or 3 for p-value matrix.")
  }
}




df <- read_excel("原始数据.xlsx")
#df1=df1[-3,]
#df1=df[37:68,c(5,12:20,24:27)]
#df1=df[1:68,c(5,12:20,24:27)]
df <- subset(df, group == "AN")
df1=df[,4:29]
df1 <- as.data.frame(lapply(df1, as.numeric))

t=splitheatmap(df1,15,"spearman",1)
windows(width = 8, height = 6)
t

c=splitheatmap(df1,15,"spearman",n=2)
c
b=splitheatmap(df1,15,"spearman",n=3)
b

c=as.data.frame(c)
c$RowNames <- rownames(c)

c <- c[, c(ncol(c), 1:(ncol(c)-1))]

table_output <- tab_df(c)
print(table_output)

b <- as.data.frame(b)
b$RowNames <- rownames(b)
b <- b[, c(ncol(b), 1:(ncol(b)-1))]
table_output <- tab_df(b)
print(table_output)



df2=df[,4:27]

chart.Correlation(df2,main = "Correlation Matrix", 
                  xlab = "Variables", 
                  ylab = "Variables",method ="spearman")
                  
                  
result=cor(df2,method ="spearman")                
result=as.data.frame(result)  
# 将行名添加在第一列
result$RowNames <- rownames(result)
# 将其余4列向后移动一列
result <- cbind(result[, 5], result[, 1:4])
# 删除原始的行名列
result$RowNames <- NULL
# 将第一列的列名设置为空
colnames(result)[1] <- "变量"
table_output <- tab_df(result)
print(table_output)                

p_value_matrix <- matrix(NA, nrow = ncol(df2), ncol = ncol(df2))    

for (i in 1:(ncol(df2)-1)){
  for (j in (i+1):ncol(df2)){
    cor_test <- cor.test(df2[,i], df2[,j],method ="spearman")
    p_value_matrix[i,j] <- cor_test$p.value
    p_value_matrix[j,i] <- cor_test$p.value
  }
}

result=p_value_matrix
result=as.data.frame(result) 
# 将行名添加在第一列
result$RowNames <- rownames(result)
# 将其余4列向后移动一列
result <- cbind(result[, 5], result[, 1:4])
# 删除原始的行名列
result$RowNames <- NULL
# 将第一列的列名设置为空
colnames(result)[1] <- "变量"
table_output <- tab_df(result)
print(table_output)  

